# -*- coding: utf-8 -*-
"""NLP1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k9Bge2p6o3BaPUMGyYX4j7Dc-kYLzGju
"""

import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

# Download required NLTK data (only needed once)
nltk.download('punkt')
nltk.download('wordnet')

# Input sentence
text = input("Enter a sentence: ")

# Tokenization
tokens = word_tokenize(text)

# Stemming
stemmer = PorterStemmer()
stemmed_words = [stemmer.stem(word) for word in tokens]

# Lemmatization
lemmatizer = WordNetLemmatizer()
lemmatized_words = [lemmatizer.lemmatize(word) for word in tokens]

# Output
print("\nOriginal Text:")
print(text)

print("\nTokens:")
print(tokens)

print("\nStemmed Words:")
print(stemmed_words)

print("\nLemmatized Words:")
print(lemmatized_words)

print("\nComparison:")
print("Stemming reduces words to root forms, which may not always be meaningful.")
print("Lemmatization converts words to meaningful base forms.")

import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')