# -*- coding: utf-8 -*-
"""NLP4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1auoQ2OmX3aw8jCWDaL8oAxKyZ7pThhzo
"""

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.decomposition import TruncatedSVD

docs = []

# Get number of documents
n = int(input("Enter number of documents: "))

# Input documents
for i in range(n):
    docs.append(input("Enter document: "))

# Input query
query = input("\nEnter search query: ")

# TF-IDF Vectorization
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(docs)

# Convert query to TF-IDF vector
query_vec = vectorizer.transform([query])

# Compute cosine similarity
scores = cosine_similarity(query_vec, X)

print("\nTF-IDF Similarity Scores:")
for i, s in enumerate(scores[0]):
    print("Document", i + 1, ":", round(s, 3))

# Apply LSA using Truncated SVD
svd = TruncatedSVD(n_components=2)
X_lsa = svd.fit_transform(X)
query_lsa = svd.transform(query_vec)

# Compute LSA similarity
lsa_scores = cosine_similarity(query_lsa, X_lsa)

print("\nLSA Similarity Scores:")
for i, s in enumerate(lsa_scores[0]):
    print("Document", i + 1, ":", round(s, 3))

# Find most relevant document
best = np.argmax(lsa_scores)

print("\nMost Relevant Document:")
print(docs[best])